"""Change interval_type from Enum to String

Revision ID: 78e155571313
Revises: 690bbd21be15
Create Date: 2025-05-06 20:59:07.722971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e155571313'
down_revision: Union[str, None] = '690bbd21be15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_intervals', 'interval_type',
               existing_type=postgresql.INTERVAL(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'one_minute'::intervaltype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_intervals', 'interval_type',
               existing_type=sa.String(length=20),
               type_=postgresql.INTERVAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'one_minute'::intervaltype"))
    # ### end Alembic commands ###
