"""Add interval_type to TimeInterval

Revision ID: aa8549fa6e15
Revises: 
Create Date: 2025-05-06 20:37:36.324903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8549fa6e15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interval_type = sa.Enum('one_minute', 'five_minutes', 'ten_minutes', name='intervaltype')
    interval_type.create(op.get_bind(), checkfirst=True)
    op.add_column('time_intervals', sa.Column('interval_type', interval_type, nullable=False, server_default='one_minute'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_intervals', 'interval_type')
    interval_type = sa.Enum('one_minute', 'five_minutes', 'ten_minutes', name='intervaltype')
    interval_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
